# Generated by Django 3.2.2 on 2021-05-12 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_auto_20210512_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='contact_address',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='contact_phone_2',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
