# Generated by Django 3.2.3 on 2021-05-17 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0003_auto_20210512_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='is_internal',
            field=models.BooleanField(default=True),
        ),
    ]
