# Generated by Django 3.2.3 on 2021-05-17 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0004_provider_is_internal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='is_internal',
        ),
        migrations.AddField(
            model_name='provider',
            name='owned_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='providers.municipality',
            ),
        ),
    ]
