# Generated by Django 3.2.3 on 2021-05-24 15:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0005_auto_20210517_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostalCode',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=255)),
                (
                    'number',
                    models.IntegerField(
                        unique=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(9999),
                        ],
                    ),
                ),
            ],
            options={
                'verbose_name': 'Postnummer',
                'verbose_name_plural': 'Postnumre',
            },
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'verbose_name': 'Sprog', 'verbose_name_plural': 'Sprog'},
        ),
        migrations.AlterModelOptions(
            name='municipality',
            options={'verbose_name': 'Kommune', 'verbose_name_plural': 'Kommuner'},
        ),
        migrations.AlterModelOptions(
            name='provider',
            options={'verbose_name': 'Tilbud', 'verbose_name_plural': 'Tilbud'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'Region', 'verbose_name_plural': 'Regioner'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Ydelser'},
        ),
        migrations.AlterModelOptions(
            name='servicecategory',
            options={
                'verbose_name': 'Ydelsestype',
                'verbose_name_plural': 'Ydelsestyper',
            },
        ),
        migrations.AlterModelOptions(
            name='socialworker',
            options={
                'verbose_name': 'Socialrådgiver',
                'verbose_name_plural': 'Socialrådgivere',
            },
        ),
        migrations.AlterModelOptions(
            name='theme',
            options={'verbose_name': 'Tema', 'verbose_name_plural': 'Temaer'},
        ),
        migrations.AlterField(
            model_name='municipality',
            name='logo',
            field=models.ImageField(
                blank=True, null=True, upload_to='', verbose_name='Logo'
            ),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='name',
            field=models.CharField(
                max_length=255, unique=True, verbose_name='Kommunenavn'
            ),
        ),
        migrations.AlterField(
            model_name='provider',
            name='company_description',
            field=models.TextField(
                default='', max_length=2000, verbose_name='Beskrivelse af stedet'
            ),
        ),
        migrations.AlterField(
            model_name='provider',
            name='contact_address',
            field=models.CharField(
                blank=True, max_length=120, null=True, verbose_name='Adresse'
            ),
        ),
        migrations.AlterField(
            model_name='provider',
            name='contact_city',
            field=models.CharField(
                blank=True, max_length=80, null=True, verbose_name='By'
            ),
        ),
        migrations.AlterField(
            model_name='provider',
            name='contact_cvr',
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name='CVR'
            ),
        ),
        migrations.AlterField(
            model_name='provider',
            name='contact_email',
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name='Email'
            ),
        ),
        migrations.AlterField(
            model_name='provider',
            name='contact_email_2',
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name='Email 2'
            ),
        ),
        migrations.AlterField(
            model_name='provider',
            name='contact_name',
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name='Kontaktperson'
            ),
        ),
        migrations.AlterField(
            model_name='provider',
            name='contact_phone',
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name='Telefon'
            ),
        ),
        migrations.AlterField(
            model_name='provider',
            name='contact_phone_2',
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name='Telefon 2'
            ),
        ),
        migrations.AlterField(
            model_name='provider',
            name='contact_postal_code',
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(9999),
                ],
                verbose_name='Postnummer',
            ),
        ),
        migrations.AlterField(
            model_name='provider',
            name='contact_title',
            field=models.CharField(
                blank=True,
                max_length=60,
                null=True,
                verbose_name='Titel på kontaktperson',
            ),
        ),
        migrations.AlterField(
            model_name='provider',
            name='contact_website',
            field=models.URLField(blank=True, null=True, verbose_name='Hjemmeside'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='logo',
            field=models.ImageField(
                blank=True, null=True, upload_to='', verbose_name='Logo'
            ),
        ),
        migrations.AlterField(
            model_name='provider',
            name='max_age',
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Maksimumalder',
            ),
        ),
        migrations.AlterField(
            model_name='provider',
            name='min_age',
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Minimumsalder',
            ),
        ),
        migrations.AlterField(
            model_name='provider',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Navn'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='open_hours',
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name='Åbningstider'
            ),
        ),
        migrations.AlterField(
            model_name='provider',
            name='service_description',
            field=models.TextField(
                default='', max_length=2000, verbose_name='Beskrivelse af ydelse'
            ),
        ),
        migrations.AlterField(
            model_name='provider',
            name='sexes',
            field=models.CharField(
                choices=[
                    ('Både drenge og piger', 'Både drenge og piger'),
                    ('Kun drenge', 'Kun drenge'),
                    ('Kun piger', 'Kun piger'),
                ],
                default='Både drenge og piger',
                max_length=255,
                verbose_name='Køn',
            ),
        ),
        migrations.AlterField(
            model_name='provider',
            name='status_report_interval',
            field=models.CharField(
                choices=[
                    ('Statusrapport ikke oplyst', 'Statusrapport ikke oplyst'),
                    ('Statusrapport efter aftale', 'Statusrapport efter aftale'),
                    ('Ikke relevant', 'Ikke relevant'),
                    ('Status månedligt', 'Statusrapport månedligt'),
                    ('Statusrapport kvartalvis', 'Statusrapport kvartalvis'),
                    ('Statusrapport halvårligt', 'Statusrapport halvårligt'),
                    ('Statusrapport årligt', 'Statusrapport årligt'),
                ],
                default='Statusrapport ikke oplyst',
                max_length=255,
                verbose_name='Frekvens af statusrapporter',
            ),
        ),
        migrations.AlterField(
            model_name='provider',
            name='waiting_time',
            field=models.CharField(
                choices=[
                    ('Ikke oplyst', 'Ventetid ikke oplyst'),
                    ('Ingen ventetid', 'Ingen ventetid'),
                    ('Muligvis ventetid', 'Mulig ventetid'),
                ],
                default='Ikke oplyst',
                max_length=100,
                verbose_name='Ventetid',
            ),
        ),
        migrations.AlterField(
            model_name='theme',
            name='name',
            field=models.CharField(
                max_length=255, unique=True, verbose_name='Temanavn'
            ),
        ),
        migrations.AlterField(
            model_name='theme',
            name='theme_type',
            field=models.CharField(
                choices=[
                    ('Socialt', 'Socialt'),
                    ('Fysisk', 'Fysisk'),
                    ('Psykisk', 'Psykisk'),
                ],
                default='Socialt',
                max_length=255,
                verbose_name='Tematype',
            ),
        ),
        migrations.AddField(
            model_name='provider',
            name='postal_codes',
            field=models.ManyToManyField(blank=True, to='providers.PostalCode'),
        ),
    ]
