# Generated by Django 3.2.3 on 2021-05-24 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0006_auto_20210524_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkMethod',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=255, verbose_name='Metodenavn')),
                ('body', models.TextField(verbose_name='Indhold')),
                (
                    'municipalities',
                    models.ManyToManyField(blank=True, to='providers.Municipality'),
                ),
            ],
            options={
                'verbose_name': 'Metode',
                'verbose_name_plural': 'Metoder',
            },
        ),
    ]
