# Generated by Django 3.2.3 on 2021-05-24 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0007_workmethod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='contact_name',
            field=models.CharField(
                blank=True, max_length=140, null=True, verbose_name='Kontaktperson'
            ),
        ),
        migrations.AlterField(
            model_name='provider',
            name='contact_title',
            field=models.CharField(
                blank=True, max_length=60, null=True, verbose_name='Stiftet d.'
            ),
        ),
        migrations.AlterField(
            model_name='provider',
            name='open_hours',
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name='Åbningstider'
            ),
        ),
    ]
