# Generated by Django 3.2.3 on 2021-05-24 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0008_auto_20210524_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='contact_name',
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name='Kontaktperson'
            ),
        ),
        migrations.AlterField(
            model_name='provider',
            name='contact_phone',
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name='Telefon'
            ),
        ),
        migrations.AlterField(
            model_name='provider',
            name='contact_phone_2',
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name='Telefon 2'
            ),
        ),
    ]
