# Generated by Django 3.2.3 on 2021-05-24 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0009_auto_20210524_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='open_hours',
            field=models.CharField(
                blank=True, max_length=550, null=True, verbose_name='Åbningstider'
            ),
        ),
    ]
