# Generated by Django 3.2.3 on 2021-05-24 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0010_alter_provider_open_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='contact_phone',
            field=models.CharField(
                blank=True, max_length=850, null=True, verbose_name='Telefon'
            ),
        ),
    ]
