# Generated by Django 3.2.3 on 2021-05-24 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0011_alter_provider_contact_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipality',
            name='email_domain',
            field=models.CharField(
                default='asdf@asdf.dk', max_length=255, verbose_name='Emaildomæne'
            ),
            preserve_default=False,
        ),
    ]
