# Generated by Django 3.2.3 on 2021-05-24 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0012_municipality_email_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipality',
            name='email_domain',
            field=models.CharField(max_length=255, verbose_name='Emaildomæne'),
        ),
    ]
