# Generated by Django 3.2.3 on 2021-05-24 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0013_alter_municipality_email_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipality',
            name='is_member',
            field=models.BooleanField(default=False, verbose_name='Medlem'),
        ),
    ]
