# Generated by Django 3.2.3 on 2021-05-24 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0014_municipality_is_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialworker',
            name='newsletter',
            field=models.BooleanField(default=False, verbose_name='Nyhedsbred'),
        ),
    ]
