# Generated by Django 3.2.3 on 2021-05-26 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0006_auto_20210524_1523'),
        ('providers', '0016_provider_note'),
    ]

    operations = []
