# Generated by Django 3.2.3 on 2021-06-07 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0024_provider_migrated_postal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipality',
            name='feature_methods',
            field=models.BooleanField(default=True, verbose_name='Metoder aktiveret'),
        ),
        migrations.AddField(
            model_name='municipality',
            name='feature_shared_knowledge',
            field=models.BooleanField(default=False, verbose_name='Metoder aktiveret'),
        ),
    ]
