# Generated by Django 3.2.4 on 2021-06-09 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0025_auto_20210607_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipality',
            name='feature_shared_knowledge',
            field=models.BooleanField(
                default=False, verbose_name='Viden på tværs aktiveret'
            ),
        ),
        migrations.AlterField(
            model_name='socialworker',
            name='newsletter',
            field=models.BooleanField(default=False, verbose_name='Nyhedsbrev'),
        ),
    ]
