# Generated by Django 3.2.4 on 2021-07-13 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0029_auto_20210712_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='company_description',
            field=models.TextField(
                blank=True,
                default='',
                max_length=2000,
                null=True,
                verbose_name='Beskrivelse af stedet',
            ),
        ),
        migrations.AlterField(
            model_name='provider',
            name='service_description',
            field=models.TextField(
                blank=True,
                default='',
                max_length=2000,
                null=True,
                verbose_name='Beskrivelse af ydelse',
            ),
        ),
    ]
