# Generated by Django 3.2.4 on 2021-08-13 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0030_auto_20210713_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Sprog'),
        ),
    ]
