# Generated by Django 3.2.4 on 2021-08-18 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0036_is_free3'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='area',
            field=models.ManyToManyField(blank=True, to='providers.Area'),
        ),
    ]
