# Generated by Django 3.2.4 on 2021-08-25 15:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0038_2_auto_20210825_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='full_day_price',
        ),
        migrations.RemoveField(
            model_name='service',
            name='hourly_price',
        ),
    ]
