# Generated by Django 3.2.4 on 2021-08-25 15:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0037_provider_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='price_type',
            field=models.CharField(
                blank=True,
                choices=[
                    ('DAILY', 'Dagspris'),
                    ('HOURLY', 'Timepris'),
                    ('FREE', 'Gratis'),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='service',
            name='price_value',
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
