# Generated by Django 3.2.6 on 2021-09-01 16:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0039_auto_20210901_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='company_description',
            field=models.TextField(
                blank=True,
                default='',
                max_length=10000,
                null=True,
                verbose_name='Beskrivelse af stedet',
            ),
        ),
        migrations.AlterField(
            model_name='provider',
            name='max_age',
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(23),
                ],
                verbose_name='Maksimumalder',
            ),
        ),
        migrations.AlterField(
            model_name='provider',
            name='service_description',
            field=models.TextField(
                blank=True,
                default='',
                max_length=10000,
                null=True,
                verbose_name='Beskrivelse af indsats',
            ),
        ),
    ]
