# Generated by Django 3.2.6 on 2021-09-08 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0041_auto_20210907_1115'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Ydelse', 'verbose_name_plural': 'Ydelser'},
        ),
    ]
