# Generated by Django 3.2.6 on 2021-09-22 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0045_alter_provider_data_days_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='admin_first_name',
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name='Administrators fornavn',
            ),
        ),
        migrations.AddField(
            model_name='provider',
            name='admin_last_name',
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name='Administrators efternavn',
            ),
        ),
    ]
