# Generated by Django 3.2.6 on 2021-09-29 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('providers', '0046_auto_20210922_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalSubscriber',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                (
                    'info_mail_consent_given',
                    models.BooleanField(default=False, verbose_name='Nyhedsbrev'),
                ),
                (
                    'authentication_key',
                    models.CharField(max_length=255, verbose_name='Aktiveringskode'),
                ),
                (
                    'user',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Fagperson',
                'verbose_name_plural': 'Fagpersoner',
            },
        ),
    ]
