# Generated by Django 3.2.6 on 2021-09-29 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0047_professionalsubscriber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professionalsubscriber',
            name='info_mail_consent_given',
        ),
    ]
