# Generated by Django 3.2.6 on 2021-10-06 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0048_remove_professionalsubscriber_info_mail_consent_given'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalsubscriber',
            name='municipality',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='providers.municipality',
            ),
        ),
    ]
