# Generated by Django 3.2.6 on 2021-10-06 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0050_alter_professionalsubscriber_authentication_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalsubscriber',
            name='municipality',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='providers.municipality',
            ),
        ),
    ]
