# Generated by Django 3.2.6 on 2021-10-06 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0051_alter_professionalsubscriber_municipality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalsubscriber',
            name='authentication_key',
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name='Aktiveringskode'
            ),
        ),
    ]
