# Generated by Django 3.2.8 on 2021-11-10 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0053_regions_to_areas'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='for_parents',
            field=models.BooleanField(
                default=False, null=True, verbose_name='Til forældre'
            ),
        ),
    ]
