# Generated by Django 3.2.8 on 2021-11-17 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0054_service_for_parents'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='membership',
            field=models.CharField(
                choices=[
                    ('Gratis medlemskab', 'Gratis medlemskab'),
                    ('Premium medlemsskab', 'Premium medlemsskab'),
                    ('Pro medlemskab', 'Pro medlemskab'),
                ],
                default='Gratis medlemskab',
                max_length=100,
                verbose_name='Medlemstype',
            ),
        ),
    ]
