# Generated by Django 3.2.8 on 2021-11-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0056_alter_provider_membership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='data_days_checked',
        ),
        migrations.AddField(
            model_name='provider',
            name='data_checked',
            field=models.BooleanField(default=False, verbose_name='Tjekket'),
        ),
    ]
