# Generated by Django 3.2.8 on 2021-11-24 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0057_auto_20211117_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='membership',
            field=models.CharField(
                choices=[
                    ('Basis medlemskab', 'Basis medlemskab'),
                    ('Business medlemsskab', 'Business medlemsskab'),
                    ('Business PRO medlemskab', 'Business PRO medlemskab'),
                ],
                default='Basis medlemskab',
                max_length=100,
                verbose_name='Medlemstype',
            ),
        ),
    ]
