# Generated by Django 3.2.8 on 2021-11-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0058_alter_provider_membership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='membership',
            field=models.CharField(
                choices=[
                    ('Gratis medlemskab', 'Gratis medlemskab'),
                    ('Business medlemsskab', 'Business medlemsskab'),
                    ('Business PRO medlemskab', 'Business PRO medlemskab'),
                ],
                default='Gratis medlemskab',
                max_length=100,
                verbose_name='Medlemstype',
            ),
        ),
    ]
