# Generated by Django 3.2.8 on 2021-11-24 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0059_alter_provider_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='welcome_message',
            field=models.TextField(
                blank=True,
                default='',
                max_length=255,
                null=True,
                verbose_name='Kort velkomsttekst',
            ),
        ),
    ]
