# Generated by Django 3.2.8 on 2021-11-28 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0060_provider_welcome_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='method_description',
            field=models.TextField(
                blank=True,
                default='',
                max_length=10000,
                null=True,
                verbose_name='Beskrivelse af metoder/tilgang',
            ),
        ),
    ]
