# Generated by Django 3.2.8 on 2021-11-28 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0061_provider_method_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='municipality_creditations',
            field=models.ManyToManyField(
                blank=True,
                related_name='municipality_creditations',
                to='providers.Municipality',
            ),
        ),
        migrations.AlterField(
            model_name='provider',
            name='owned_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='owned_by',
                to='providers.municipality',
            ),
        ),
    ]
