# Generated by Django 3.2.8 on 2021-11-28 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0063_alter_provider_municipality_creditations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='municipality_creditations',
            field=models.ManyToManyField(
                blank=True,
                related_name='municipality_creditations',
                to='providers.Municipality',
            ),
        ),
    ]
