# Generated by Django 3.2.8 on 2021-11-30 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0066_all_providers_gain_basis_memberships'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='welcome_message',
            field=models.TextField(
                blank=True,
                default='',
                max_length=150,
                null=True,
                verbose_name='Kort velkomsttekst',
            ),
        ),
    ]
