# Generated by Django 3.2.8 on 2021-12-17 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0068_alter_provider_welcome_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipality',
            name='is_not_municipality',
            field=models.BooleanField(default=False, verbose_name='Er ikke en kommune'),
        ),
    ]
