# Generated by Django 3.2.8 on 2021-12-29 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0069_municipality_is_not_municipality'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolboxTool',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                (
                    'name',
                    models.CharField(max_length=255, verbose_name='Fagligt værktøj'),
                ),
                ('body', models.TextField(verbose_name='Indhold')),
            ],
            options={
                'verbose_name': 'Fagligt værktøj',
                'verbose_name_plural': 'Faglige værktøj',
            },
        ),
    ]
