# Generated by Django 3.2.8 on 2021-12-29 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0070_toolboxtool'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toolboxtool',
            options={
                'verbose_name': 'Fagligt værktøj',
                'verbose_name_plural': 'Faglige værktøjer',
            },
        ),
        migrations.AlterField(
            model_name='provider',
            name='welcome_message',
            field=models.TextField(
                blank=True,
                default='',
                max_length=250,
                null=True,
                verbose_name='Kort præsentation af tilbuddet',
            ),
        ),
    ]
