# Generated by Django 3.2.11 on 2022-02-15 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0072_all_providers_are_changed_to_beginner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='area',
        ),
    ]
