# Generated by Django 3.2.13 on 2022-04-22 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0075_oneoffitemsprovider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='is_internal',
        ),
    ]
