# Generated by Django 3.2.13 on 2022-04-22 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0076_remove_provider_is_internal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OneOffItemsProvider',
        ),
    ]
