# Generated by Django 3.2.12 on 2022-04-23 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0077_delete_oneoffitemsprovider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='welcome_message',
            field=models.TextField(
                default='Ønsker du mere information om vores tilbud, er du meget velkommen til at kontakte os.',
                max_length=250,
                verbose_name='Velkomsthilsen',
            ),
        ),
    ]
