# Generated by Django 3.2.12 on 2022-03-28 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('providers', '0073_remove_provider_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.IntegerField(null=True)),
                (
                    'user_type',
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name='Brugertype'
                    ),
                ),
                (
                    'user_organization',
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name='Organisation',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='SearchEvent',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'freetext',
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name='Fritekst'
                    ),
                ),
                (
                    'service_category',
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name='Type hjælp'
                    ),
                ),
                (
                    'gender',
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name='Køn'
                    ),
                ),
                (
                    'is_volunteer_organization',
                    models.BooleanField(
                        blank=True, null=True, verbose_name='Frivilligt tilbud'
                    ),
                ),
                (
                    'base_event',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='analytics.analyticsevent',
                    ),
                ),
                (
                    'creditations',
                    models.ManyToManyField(blank=True, to='providers.Creditation'),
                ),
                (
                    'languages',
                    models.ManyToManyField(blank=True, to='providers.Language'),
                ),
                (
                    'postal_codes',
                    models.ManyToManyField(blank=True, to='providers.PostalCode'),
                ),
                ('themes', models.ManyToManyField(blank=True, to='providers.Theme')),
            ],
        ),
        migrations.CreateModel(
            name='RegisterEvent',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'base_event',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='analytics.analyticsevent',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='PageViewEvent',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('page_path', models.CharField(max_length=255)),
                (
                    'base_event',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='analytics.analyticsevent',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='LoginEvent',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'base_event',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='analytics.analyticsevent',
                    ),
                ),
            ],
        ),
    ]
