"""
Django settings for boernebasen project.

Generated by 'django-admin startproject' using Django 3.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

import sys
import os
import dj_database_url
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(0^9ivtc-#(eplg*2z55^dzx7&fr(wgc4z#q3$du__jy0xq9dn'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'localhost', '0.0.0.0', 'python-apps-d4web.herokuapp.com', '127.0.0.1',
]

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'storages',
    'accounts',
    'providers',
    'sso',
    'rest_framework',
    'widget_tweaks',
    'anymail',
    'mailchimp_marketing',
    'mailchimp_marketing.api_client',
    'analytics',
    'authentication',
]

# MAILCHIMP CREDENTIALS
MAILCHIMP_API_KEY = '3ac787a9aaf1df0b77705832e02b2a2d-us19'
MAILCHIMP_DATA_CENTER = 'us19'
MAILCHIMP_EMAIL_LIST_ID_PROVIDERS = '2a8b0e7879'
MAILCHIMP_EMAIL_LIST_ID_SOCIAL_WORKERS = '7f467f8a96'

# Email
#  DEFAULT_FROM_EMAIL = 'Lucky Botaru Support <support@boernebasen.dk>'
#  EMAIL_HOST = 'smpt.eu.mailgun.org'
#  EMAIL_PORT = 587
#  EMAIL_HOST_USER = 'noreply@epost.boernebasen.dk'
#  EMAIL_HOST_PASSWORD = "3kh9umujora5" # "ee81cfe1ae36ad93b923b7c2710a9aaf-90ac0eb7-727d7ba0"
#  EMAIL_USE_TLS = True

ANYMAIL = {
    #"MAILGUN_API_KEY": 'fba46aa3ffcb8f78c2dca638e4d88f7e-90ac0eb7-325255f5',
    #"MAILGUN_SENDER_DOMAIN": 'epost.boernebasen.dk',
    #"MAILGUN_API_URL": 'https://api.eu.mailgun.net/v3',
    #"DEBUG_API_REQUESTS": True,
    "SENDINBLUE_API_KEY": "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",
    "SENDINBLUE_API_URL": "https://api.sendinblue.com/v3/"
}
# or sendgrid.EmailBackend, or...
EMAIL_BACKEND = "anymail.backends.sendinblue.EmailBackend"
#EMAIL_BACKEND = "anymail.backends.mailgun.EmailBackend"
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend' # change smtp to console to show sent emails in server log
# if you don't already have this in settings
DEFAULT_FROM_EMAIL = "noreply@boernebasen.dk"
SERVER_EMAIL = "admin@boernebasen.dk"

# Application definition
REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    'DEFAULT_PERMISSION_CLASSES':
    ['rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly']
}

# Auth settings
AUTH_USER_MODEL = 'accounts.CustomUser'

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/profile/'
LOGOUT_REDIRECT_URL = '/login'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'boernebasen.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'boernebasen.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {}
#DATABASES['default'] = dj_database_url.config(default='postgres://jlipojtftqfyib:b1d6e2fd2e2e6c84b28e8abcc6a8d9c5bba9f2cd7992ff7d3e42507532801a5e@ec2-54-76-43-89.eu-west-1.compute.amazonaws.com:5432/d3c25konmb710a')
#DATABASES['default'] = dj_database_url.config(default='postgres://jlipojtftqfyib:b1d6e2fd2e2e6c84b28e8abcc6a8d9c5bba9f2cd7992ff7d3e42507532801a5e@ec2-54-76-43-89.eu-west-1.compute.amazonaws.com:5432/d3c25konmb710a')
DATABASES['default'] = dj_database_url.config(default='postgres://fstiwhvptwwvdx:c77046680fe4b1f2f0cd87c6ed6cf4aa36df6e15fc5ec0c91326e2058b28e4b1@ec2-54-220-86-118.eu-west-1.compute.amazonaws.com:5432/d69lqe8m3vb4i7')

#DATABASES['default'] = dj_database_url.config()

""" DATABASES = {
    'default': {
        'NAME': 'testdb',
        'USER': 'postgres',
        'PASSWORD': 'jorhendz',
        'HOST': '127.0.0.1', 'PORT': 5434,
        'CONN_MAX_AGE': 0,
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'TEST': {
            'NAME': 'mytestdatabase',
        },
    }
} """

PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
    'accounts.hashers.BBOldHasher',
]

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME':
        'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME':
        'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME':
        'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME':
        'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'da-dk'

DATA_UPLOAD_MAX_NUMBER_FIELDS = 10240

TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATIC_URL = '/static/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# Simplified static file serving.
# https://warehouse.python.org/project/whitenoise/

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files (Uploaded files)

AWS_ACCESS_KEY_ID = 'IBXQN25L72WE7WAJZIJ7'
AWS_SECRET_ACCESS_KEY = 'CA/r0br54jtF1Yy2IV+5WUC4GV7Gtwt35bC8o56NfWg'
AWS_STORAGE_BUCKET_NAME = 'boernebasen-dev'
AWS_S3_ENDPOINT_URL = 'https://fra1.digitaloceanspaces.com'
AWS_S3_CUSTOM_DOMAIN = 'boernebasen-dev.fra1.digitaloceanspaces.com'

AWS_S3_FILE_OVERWRITE = False
AWS_S3_OBJECT_PARAMETERS = {
    'CacheControl': 'max-age=86400',
}
AWS_LOCATION = 'media'
AWS_DEFAULT_ACL = 'public-read'
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Azure AD Setting for SSO
SSO_SCOPES = ["User.Read"]
SSO_REDIRECT = 'https://python-apps-d4web.herokuapp.com/sso/callback'
SSO_AUTHORITY = 'https://login.microsoftonline.com/common'
SSO_CLIENT_ID = '53732564-6608-457e-9591-8fb291cf4c3d'
SSO_CLIENT_SECRET = 'B7r3420OuSea-eAE7iG-Ned-D~3.88Emfc'




#Stripe related values, should be changed to actual after testing
STRIPE_ENDPOINT_SECRET = 'whsec_15eb21950cab0f612c74c78b5921dea133718dd3ca6c266f6525f557885620ba'

#these values are the actual values
STRIPE_PAYMENT_LINK_BASIS_ANNUAL = 'https://buy.stripe.com/fZeaF46BHewr5Nu002'
STRIPE_PAYMENT_LINK_BASIS_MONTHLY = 'https://buy.stripe.com/8wM00q0dj0FB0tadQR'
STRIPE_PAYMENT_LINK_EXPERT = 'https://buy.stripe.com/8wM8wW3pv5ZV6Ry000'