# Generated by Django 3.2.3 on 2021-05-24 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210524_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name='Navn'
            ),
        ),
    ]
