# Generated by Django 3.2.3 on 2021-05-25 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='old_email',
            field=models.CharField(
                blank=True,
                default=None,
                max_length=255,
                null=True,
                verbose_name='Gammel email',
            ),
        ),
    ]
