# Generated by Django 3.2.3 on 2021-05-25 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_old_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='migration_notes',
            field=models.TextField(
                default='', max_length=20000, verbose_name='Migrationsoplysninger'
            ),
        ),
    ]
