# Generated by Django 3.2.6 on 2021-09-01 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_migration_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='consent',
            field=models.BooleanField(default=False, verbose_name='Samtykke'),
        ),
    ]
