# Generated by Django 3.2.6 on 2021-09-01 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_consent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='consent',
        ),
        migrations.AddField(
            model_name='customuser',
            name='consent_given',
            field=models.BooleanField(default=False, verbose_name='Samtykke'),
        ),
    ]
