# Generated by Django 3.2.6 on 2021-09-01 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_set_all_consent_to_true'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='info_mail_consent_given',
            field=models.BooleanField(
                default=False, verbose_name='Samtykke til infomail givet'
            ),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='consent_given',
            field=models.BooleanField(default=False, verbose_name='Samtykke givet'),
        ),
    ]
