# Generated by Django 3.2.6 on 2021-09-01 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_set_all_consent_to_true2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='consent_given',
            field=models.BooleanField(
                default=False, verbose_name='Samtykke til GDPR givet'
            ),
        ),
    ]
