# Generated by Django 3.2.6 on 2021-09-22 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_name_formats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name='Fornavn'
            ),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name='Efternavn'
            ),
        ),
    ]
