# Generated by Django 3.2.12 on 2022-03-26 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_creating_admin_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_analytics_event',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
